export const dummyVideos = [
  {
    id: "1",
    title: "Exploring the Mountains",
    thumbnails: "2.png",
    video: "https://example.com/videos/mountain.mp4",
    userId: "Shubham",
    views: "1.2M",
    likes: "300K",
    dislikes: "10K",
    uploadedAt: "1 week ago",
    updatedAt: "1 week ago",
    description: "Join us on an epic adventure to the tallest mountains!",
    duration: "10:23",
    tags: ["travel", "mountains", "vlog"],
    category: ["Travel", "Adventure"],
    commentsCount: "200",
    comments: [
      "Amazing views!",
      "Loved the drone shots",
      "Where is this place?",
    ],
    subscribersCount: "1.5M",
    subscribers: ["user1", "user2", "user3"],
  },
  {
    id: "2",
    title: "JavaScript Async/Await Crash Course",
    thumbnails: "3.png",
    video: "https://example.com/videos/js_async.mp4",
    userId: "CodeMaster",
    views: "850K",
    likes: "75K",
    dislikes: "2K",
    uploadedAt: "3 days ago",
    updatedAt: "2 days ago",
    description:
      "Learn how async/await works in JavaScript in this quick tutorial!",
    duration: "8:45",
    tags: ["javascript", "async", "webdev"],
    category: ["Education", "Programming"],
    commentsCount: "150",
    comments: ["So helpful!", "Thanks bro", "I finally understand async!"],
    subscribersCount: "250K",
    subscribers: ["dev123", "frontendguru", "webninja"],
  },
  {
    id: "3",
    title: "Top 10 Football Goals of 2024",
    thumbnails: "4.png",
    video: "https://example.com/videos/goals2024.mp4",
    userId: "SportsFan",
    views: "2.4M",
    likes: "500K",
    dislikes: "5K",
    uploadedAt: "4 days ago",
    updatedAt: "4 days ago",
    description:
      "A compilation of the most stunning football goals of the year!",
    duration: "12:00",
    tags: ["football", "sports", "highlights"],
    category: ["Sports"],
    commentsCount: "600",
    comments: ["Goal #7 was insane!", "Messi is the GOAT", "Where’s Ronaldo?"],
    subscribersCount: "950K",
    subscribers: ["fan1", "baller22", "goalkeeperlife"],
  },
  {
    id: "4",
    title: "Relaxing Lofi Beats – Study & Chill",
    thumbnails: "1.png",
    video: "https://example.com/videos/lofi.mp4",
    userId: "BeatZone",
    views: "3.1M",
    likes: "410K",
    dislikes: "1K",
    uploadedAt: "2 weeks ago",
    updatedAt: "1 week ago",
    description:
      "Enjoy smooth and relaxing lofi beats to help you stay focused.",
    duration: "59:59",
    tags: ["lofi", "music", "study"],
    category: ["Music", "Chill"],
    commentsCount: "870",
    comments: ["Helps me sleep", "Pure vibe", "Best playlist ever"],
    subscribersCount: "2.2M",
    subscribers: ["studymate", "zenmode", "lofigang"],
  },
  {
    id: "7",
    title: "Top 10 Football Goals of 2024",
    thumbnails: "4.png",
    video: "https://example.com/videos/goals2024.mp4",
    userId: "SportsFan",
    views: "2.4M",
    likes: "500K",
    dislikes: "5K",
    uploadedAt: "4 days ago",
    updatedAt: "4 days ago",
    description:
      "A compilation of the most stunning football goals of the year!",
    duration: "12:00",
    tags: ["football", "sports", "highlights"],
    category: ["Sports"],
    commentsCount: "600",
    comments: ["Goal #7 was insane!", "Messi is the GOAT", "Where’s Ronaldo?"],
    subscribersCount: "950K",
    subscribers: ["fan1", "baller22", "goalkeeperlife"],
  },
  {
    id: "5",
    title: "Exploring the Mountains",
    thumbnails: "2.png",
    video: "https://example.com/videos/mountain.mp4",
    userId: "Shubham",
    views: "1.2M",
    likes: "300K",
    dislikes: "10K",
    uploadedAt: "1 week ago",
    updatedAt: "1 week ago",
    description: "Join us on an epic adventure to the tallest mountains!",
    duration: "10:23",
    tags: ["travel", "mountains", "vlog"],
    category: ["Travel", "Adventure"],
    commentsCount: "200",
    comments: [
      "Amazing views!",
      "Loved the drone shots",
      "Where is this place?",
    ],
    subscribersCount: "1.5M",
    subscribers: ["user1", "user2", "user3"],
  },
  {
    id: "6",
    title: "JavaScript Async/Await Crash Course",
    thumbnails: "3.png",
    video: "https://example.com/videos/js_async.mp4",
    userId: "CodeMaster",
    views: "850K",
    likes: "75K",
    dislikes: "2K",
    uploadedAt: "3 days ago",
    updatedAt: "2 days ago",
    description:
      "Learn how async/await works in JavaScript in this quick tutorial!",
    duration: "8:45",
    tags: ["javascript", "async", "webdev"],
    category: ["Education", "Programming"],
    commentsCount: "150",
    comments: ["So helpful!", "Thanks bro", "I finally understand async!"],
    subscribersCount: "250K",
    subscribers: ["dev123", "frontendguru", "webninja"],
  },
];
